env:
  secrets:
    TFE_DATABASE_PASSWORD: ${TFE_DATABASE_PASSWORD}
    TFE_ENCRYPTION_PASSWORD: ${TFE_ENCRYPTION_PASSWORD}
    TFE_LICENSE: ${TFE_LICENSE}
    TFE_OBJECT_STORAGE_S3_SERVER_SIDE_ENCRYPTION_KMS_KEY_ID: ${TFE_OBJECT_STORAGE_S3_SERVER_SIDE_ENCRYPTION_KMS_KEY_ID}
    TFE_REDIS_PASSWORD: ${TFE_REDIS_PASSWORD}
  variables:
    TFE_CAPACITY_CONCURRENCY: ${TFE_CAPACITY_CONCURRENCY}
    TFE_DATABASE_HOST: ${TFE_DATABASE_HOST}
    TFE_DATABASE_NAME: ${TFE_DATABASE_NAME}
    TFE_DATABASE_PARAMETERS: ${TFE_DATABASE_PARAMETERS}
    TFE_DATABASE_USER: ${TFE_DATABASE_USER}
    TFE_HOSTNAME: ${TFE_HOSTNAME}
    TFE_IACT_SUBNETS: ${TFE_IACT_SUBNETS}
    TFE_OBJECT_STORAGE_S3_BUCKET: ${TFE_OBJECT_STORAGE_S3_BUCKET}
    TFE_OBJECT_STORAGE_S3_ENDPOINT: ${TFE_OBJECT_STORAGE_S3_ENDPOINT}
    TFE_OBJECT_STORAGE_S3_REGION: ${TFE_OBJECT_STORAGE_S3_REGION}
    TFE_OBJECT_STORAGE_S3_SERVER_SIDE_ENCRYPTION: ${TFE_OBJECT_STORAGE_S3_SERVER_SIDE_ENCRYPTION}
    TFE_OBJECT_STORAGE_S3_USE_INSTANCE_PROFILE: ${TFE_OBJECT_STORAGE_S3_USE_INSTANCE_PROFILE}
    TFE_OBJECT_STORAGE_TYPE: ${TFE_OBJECT_STORAGE_TYPE}
    TFE_REDIS_HOST: ${TFE_REDIS_HOST}
    TFE_REDIS_USE_AUTH: ${TFE_REDIS_USE_AUTH}
    TFE_REDIS_USE_TLS: ${TFE_REDIS_USE_TLS}
imagePullSecrets:
  - name: terraform-enterprise
image:
  name: ${IMAGE_NAME}
  repository: ${IMAGE_REPOSITORY}
  tag: ${IMAGE_TAG}
replicaCount: ${REPLICA_COUNT}
tfe:
  privateHttpPort: ${PRIVATE_HTTP_PORT}
  privateHttpsPort: ${PRIVATE_HTTPS_PORT}
tls:
  caCertData: ${TLS_CA_CERT_DATA}
  certData: ${TLS_CERT_DATA}
  keyData: ${TLS_KEY_DATA}